language: python
cache: pip
matrix:
  include:
    - python: "3.4"
    - python: "3.5"
    - python: "3.6"
    - python: "3.7"
    - python: "3.8"
      dist: xenial    # required for Python 3.7 (travis-ci/travis-ci#9069)
      sudo: required  # required for Python 3.7 (travis-ci/travis-ci#9069)

# command to install dependencies
install: "pip install -r requirements.txt"

before_script:
  - pip install flake8
  # stop the build if there are Python syntax errors or undefined names
  - flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
  # exit-zero treats all errors as warnings.
  - flake8 . --count --exit-zero --max-complexity=10 --statistics

# command to run tests
script: nosetests
