[tox]
envlist = py312
recreate = True

[testenv]
basepython = python3.12
deps =
    -r{toxinidir}/requirements.txt
    -r{toxinidir}/requirements-test.txt
commands = python -m pytest howdou/tests.py -v {posargs}
