# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master, vscode-ext]
    paths: [ 'extension/**']
  pull_request:
    branches: [ master ]
    paths: [ 'extension/**']
  
jobs:
  
    job_1:
      name: Plugin

      runs-on: macos-latest

      strategy:
        matrix:
          node-version: [10.x, 12.x, 14.x]
      
      steps:
        - uses: actions/checkout@v2
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node-version }}
        - run: |
            npm ci
            npm run build --if-present
            npm run lint
            npm test
          working-directory: ./extension/code-editor-integration
    
    job_2:
      name: Vscode Ext

      runs-on: macos-latest

      strategy:
        matrix:
          node-version: [10.x, 12.x, 14.x]

      steps:
        - uses: actions/checkout@v2
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node-version }}
        - run: |
            npm ci
            npm run build --if-present
            npm run precompile
            npm run lint
            npm test
          working-directory: ./extension/vscode-howdoi
